# This workflow will publish a new version of this repository as an NPM package. A commit will also be made to update the version of the package.json.
name: Build & Publish to NPM

on:
  workflow_dispatch:
  
  # Only when there is a push that affects files outside of the package.json and package-lock.json, run this workflow.
  push:
    branches:
      - main
    paths-ignore:
      - package.json
      - package-lock.json
      - '**/package.json'
      - '**/package-lock.json'
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    
    - name: Set git user name
      run: git config --global user.name 'Github Bot'
      
    - name: Set git user email
      run: git config --global user.email '${{secrets.GH_EMAIL}}'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: NPM Install
      run: npm install

    - name: Install Angular CLI
      run: npm i -g @angular/cli@15.0.1

    - name: Increment Version & Publish to NPM
      run: bash ./publish.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
